function Graphical_Abstract_3DPlot(outputFolder)
%% Simulated compositional hand-eye tuning surface
%
% MATLAB R2021a compatible
%
% Creates:
%   Figure 1: Three-dimensional compositional tuning surface
%   Figure 2: Mean hand-direction tuning curve
%   Figure 3: Mean eye-direction tuning curve
%
% All figures are exported as PDFs.

close all;

if nargin < 1 || isempty(outputFolder)
    repoRoot = fileparts(fileparts(fileparts(mfilename('fullpath'))));
    dataRoot = fullfile(fileparts(fileparts(repoRoot)), ...
        'Data', 'HE_coord', 'data');
    outputFolder = fullfile(dataRoot, 'plots', ...
        'graphical_abstract_components');
end

%% ========================================================================
% Adjustable parameters
% =========================================================================

% Surface resolution
nGrid = 181;

% Simulated tuning parameters
baseline      = 10;       % Mean firing rate [Hz]
handAmplitude = 3;        % Hand modulation amplitude [Hz]
eyeAmplitude  = 3;        % Eye modulation amplitude [Hz]

handPhase = -pi/2;
eyePhase  = -pi;

% Surface appearance
surfaceAlpha  = 0.80;
surfaceShrink = 0.80;

% Spacing between surface and projection walls
wallOffsetFraction  = 0.30;
floorOffsetFraction = 0.10;
topOffsetFraction   = 0.10;

% Curve appearance
meanLineWidth = 5;

% Grid appearance
gridLineWidth = 0.75;
gridColor     = [0.76, 0.79, 0.82];
wallColor     = [0.975, 0.978, 0.982];

% Curve colors
handLineColor = [0.10, 0.32, 0.78];
eyeLineColor  = [0.82, 0.16, 0.16];

% Camera
cameraAzimuth   = -135;
cameraElevation = 20;

% Global text-size multiplier
%
% 1.0 = original size
% 2.0 = twice as large
% 3.0 = three times as large
textScale = 2.0;

% Figure sizes
figureWidth  = 15.0;
figureHeight = 12.0;

curveFigureWidth  = 10.0;
curveFigureHeight = 8.0;

% Fixed firing-rate limits
frMin = -2;
frMax = 20;

% Saving
saveFigures = true;

surfaceOutputName = ...
    'Simulated_Compositional_HandEye_Surface.pdf';

handOutputName = ...
    'Simulated_Hand_Tuning_Curve.pdf';

eyeOutputName = ...
    'Simulated_Eye_Tuning_Curve.pdf';

%% ========================================================================
% Simulate the hand-eye tuning surface
% =========================================================================

thetaHand = linspace(-pi, pi, nGrid);
thetaEye  = linspace(-pi, pi, nGrid);

[TH, TE] = meshgrid(thetaHand, thetaEye);

handComponent = ...
    handAmplitude .* sin(TH - handPhase);

eyeComponent = ...
    eyeAmplitude .* cos(TE - eyePhase);

FR = baseline + handComponent + eyeComponent;

%% ========================================================================
% One-dimensional mean tuning curves
% =========================================================================

meanHandCurve = ...
    baseline + handAmplitude .* sin(thetaHand - handPhase);

meanEyeCurve = ...
    baseline + eyeAmplitude .* cos(thetaEye - eyePhase);

%% ========================================================================
% Shrink the displayed surface toward the center
% =========================================================================

THplot = surfaceShrink .* TH;
TEplot = surfaceShrink .* TE;

%% ========================================================================
% Cube limits and wall locations
% =========================================================================

frRange = frMax - frMin;

zFloor = ...
    frMin - floorOffsetFraction .* frRange;

zTop = ...
    frMax + topOffsetFraction .* frRange;

wallOffset = ...
    wallOffsetFraction .* (2*pi);

xWall = -pi - wallOffset;
yWall =  pi + wallOffset;

xLimits = [xWall, pi];
yLimits = [-pi, yWall];
zLimits = [zFloor, zTop];

%% ========================================================================
% Shared ticks and labels
% =========================================================================

angularGridTicks = ...
    [-pi, -pi/2, 0, pi/2, pi];

angleTickLabels = { ...
    '-\pi', ...
    '-\pi/2', ...
    '0', ...
    '\pi/2', ...
    '\pi'};

zGridTicks = ...
    5 * ceil(zFloor/5) : 5 : 5 * floor(zTop/5);

curveYTicks = ...
    5 * ceil(frMin/5) : 5 : 5 * floor(frMax/5);

%% ========================================================================
% Custom colormap
% =========================================================================

nColors = 256;

colorAnchors = [
    0.04, 0.08, 0.28
    0.00, 0.35, 0.68
    0.08, 0.68, 0.76
    0.95, 0.84, 0.26
    0.86, 0.20, 0.08
];

anchorLocations = ...
    linspace(0, 1, size(colorAnchors,1));

queryLocations = ...
    linspace(0, 1, nColors);

customMap = interp1( ...
    anchorLocations, ...
    colorAnchors, ...
    queryLocations, ...
    'pchip');

customMap(customMap < 0) = 0;
customMap(customMap > 1) = 1;

%% ========================================================================
% FIGURE 1: Three-dimensional compositional surface
% =========================================================================

figSurface = figure( ...
    'Color', 'w', ...
    'Units', 'inches', ...
    'Position', [0.5, 0.5, figureWidth, figureHeight], ...
    'Renderer', 'opengl');

ax = axes( ...
    'Parent', figSurface, ...
    'Units', 'normalized', ...
    'Position', [0.16, 0.22, 0.60, 0.65]);

hold(ax, 'on');

%% ------------------------------------------------------------------------
% Transparent projection planes
% -------------------------------------------------------------------------

patch( ...
    [xLimits(1), xLimits(2), xLimits(2), xLimits(1)], ...
    [yLimits(1), yLimits(1), yLimits(2), yLimits(2)], ...
    [zFloor, zFloor, zFloor, zFloor], ...
    wallColor, ...
    'Parent', ax, ...
    'EdgeColor', 'none', ...
    'FaceAlpha', 0);

patch( ...
    [xWall, xWall, xWall, xWall], ...
    [yLimits(1), yLimits(2), yLimits(2), yLimits(1)], ...
    [zFloor, zFloor, zTop, zTop], ...
    wallColor, ...
    'Parent', ax, ...
    'EdgeColor', 'none', ...
    'FaceAlpha', 0);

patch( ...
    [xLimits(1), xLimits(2), xLimits(2), xLimits(1)], ...
    [yWall, yWall, yWall, yWall], ...
    [zFloor, zFloor, zTop, zTop], ...
    wallColor, ...
    'Parent', ax, ...
    'EdgeColor', 'none', ...
    'FaceAlpha', 0);

%% ------------------------------------------------------------------------
% Grid lines on eye-direction wall: x = xWall
% -------------------------------------------------------------------------

for k = 1:length(angularGridTicks)

    yValue = angularGridTicks(k);

    plot3( ...
        ax, ...
        [xWall, xWall], ...
        [yValue, yValue], ...
        [zFloor, zTop], ...
        'Color', gridColor, ...
        'LineWidth', gridLineWidth);

end

for k = 1:length(zGridTicks)

    zValue = zGridTicks(k);

    plot3( ...
        ax, ...
        [xWall, xWall], ...
        [yLimits(1), yLimits(2)], ...
        [zValue, zValue], ...
        'Color', gridColor, ...
        'LineWidth', gridLineWidth);

end

%% ------------------------------------------------------------------------
% Grid lines on hand-direction wall: y = yWall
% -------------------------------------------------------------------------

for k = 1:length(angularGridTicks)

    xValue = angularGridTicks(k);

    plot3( ...
        ax, ...
        [xValue, xValue], ...
        [yWall, yWall], ...
        [zFloor, zTop], ...
        'Color', gridColor, ...
        'LineWidth', gridLineWidth);

end

for k = 1:length(zGridTicks)

    zValue = zGridTicks(k);

    plot3( ...
        ax, ...
        [xLimits(1), xLimits(2)], ...
        [yWall, yWall], ...
        [zValue, zValue], ...
        'Color', gridColor, ...
        'LineWidth', gridLineWidth);

end

%% ------------------------------------------------------------------------
% Three-dimensional surface
% -------------------------------------------------------------------------

surf( ...
    ax, ...
    THplot, ...
    TEplot, ...
    FR, ...
    FR, ...
    'FaceColor', 'interp', ...
    'EdgeColor', 'none', ...
    'FaceAlpha', surfaceAlpha);

%% ------------------------------------------------------------------------
% Mean hand projection
% -------------------------------------------------------------------------

plot3( ...
    ax, ...
    thetaHand, ...
    yWall .* ones(size(thetaHand)), ...
    meanHandCurve, ...
    'Color', handLineColor, ...
    'LineWidth', meanLineWidth);

%% ------------------------------------------------------------------------
% Mean eye projection
% -------------------------------------------------------------------------

plot3( ...
    ax, ...
    xWall .* ones(size(thetaEye)), ...
    thetaEye, ...
    meanEyeCurve, ...
    'Color', eyeLineColor, ...
    'LineWidth', meanLineWidth);

%% ------------------------------------------------------------------------
% Surface outlines
% -------------------------------------------------------------------------

outlineColor = [0.12, 0.12, 0.12];

plot3( ...
    ax, THplot(1,:), TEplot(1,:), FR(1,:), ...
    'Color', outlineColor, ...
    'LineWidth', 0.75);

plot3( ...
    ax, THplot(end,:), TEplot(end,:), FR(end,:), ...
    'Color', outlineColor, ...
    'LineWidth', 0.75);

plot3( ...
    ax, THplot(:,1), TEplot(:,1), FR(:,1), ...
    'Color', outlineColor, ...
    'LineWidth', 0.75);

plot3( ...
    ax, THplot(:,end), TEplot(:,end), FR(:,end), ...
    'Color', outlineColor, ...
    'LineWidth', 0.75);

%% ------------------------------------------------------------------------
% Foreground cube edges
% -------------------------------------------------------------------------

cubeEdgeColor = [0.35, 0.37, 0.40];
cubeEdgeWidth = 1.05;

% Eye-wall bottom edge
plot3( ...
    ax, ...
    [xWall, xWall], ...
    [yLimits(1), yLimits(2)], ...
    [zFloor, zFloor], ...
    'Color', cubeEdgeColor, ...
    'LineWidth', cubeEdgeWidth);

% Eye-wall top edge
plot3( ...
    ax, ...
    [xWall, xWall], ...
    [yLimits(1), yLimits(2)], ...
    [zTop, zTop], ...
    'Color', cubeEdgeColor, ...
    'LineWidth', cubeEdgeWidth);

% Eye-wall outer vertical edge
plot3( ...
    ax, ...
    [xWall, xWall], ...
    [yLimits(1), yLimits(1)], ...
    [zFloor, zTop], ...
    'Color', cubeEdgeColor, ...
    'LineWidth', cubeEdgeWidth);

% Hand-wall bottom edge
plot3( ...
    ax, ...
    [xLimits(1), xLimits(2)], ...
    [yWall, yWall], ...
    [zFloor, zFloor], ...
    'Color', cubeEdgeColor, ...
    'LineWidth', cubeEdgeWidth);

% Hand-wall top edge
plot3( ...
    ax, ...
    [xLimits(1), xLimits(2)], ...
    [yWall, yWall], ...
    [zTop, zTop], ...
    'Color', cubeEdgeColor, ...
    'LineWidth', cubeEdgeWidth);

% Hand-wall outer vertical edge
plot3( ...
    ax, ...
    [xLimits(2), xLimits(2)], ...
    [yWall, yWall], ...
    [zFloor, zTop], ...
    'Color', cubeEdgeColor, ...
    'LineWidth', cubeEdgeWidth);

% Shared vertical edge
plot3( ...
    ax, ...
    [xWall, xWall], ...
    [yWall, yWall], ...
    [zFloor, zTop], ...
    'Color', cubeEdgeColor, ...
    'LineWidth', cubeEdgeWidth);

%% ------------------------------------------------------------------------
% Lighting
% -------------------------------------------------------------------------

lighting(ax, 'gouraud');
material(ax, 'dull');

camlight(ax, 35, 45);
camlight(ax, -125, 20);

%% ------------------------------------------------------------------------
% Three-dimensional axes formatting
% -------------------------------------------------------------------------

colormap(ax, customMap);
caxis(ax, [frMin, frMax]);

xlim(ax, xLimits);
ylim(ax, yLimits);
zlim(ax, zLimits);

view(ax, cameraAzimuth, cameraElevation);

axis(ax, 'vis3d');
box(ax, 'off');
grid(ax, 'off');

set(ax, ...
    'FontName', 'Arial', ...
    'FontSize', 14 * textScale, ...
    'LineWidth', 1.2, ...
    'TickDir', 'out', ...
    'TickLength', [0.012, 0.012], ...
    'XColor', [0.12, 0.12, 0.12], ...
    'YColor', [0.12, 0.12, 0.12], ...
    'ZColor', [0.12, 0.12, 0.12], ...
    'XTick', angularGridTicks, ...
    'XTickLabel', angleTickLabels, ...
    'YTick', angularGridTicks, ...
    'YTickLabel', angleTickLabels, ...
    'ZTick', zGridTicks);

% Remove automatically positioned x and y labels.
% They are replaced by non-overlapping annotations below.
xlabel(ax, '');
ylabel(ax, '');

zlabel( ...
    ax, ...
    '', ...
    'FontSize', 17 * textScale, ...
    'FontWeight', 'bold');

pbaspect(ax, [1.10, 1.10, 0.82]);

%% ------------------------------------------------------------------------
% Non-overlapping hand and eye axis labels
%
% These labels are placed in figure coordinates, so their positions do not
% change or overlap when the three-dimensional view is rotated.
% -------------------------------------------------------------------------

% annotation( ...
%     figSurface, ...
%     'textbox', ...
%     [0.08, 0.055, 0.37, 0.075], ...
%     'String', 'Eye direction, \theta_E', ...
%     'Interpreter', 'tex', ...
%     'FontName', 'Arial', ...
%     'FontSize', 17 * textScale, ...
%     'FontWeight', 'bold', ...
%     'HorizontalAlignment', 'center', ...
%     'VerticalAlignment', 'middle', ...
%     'EdgeColor', 'none', ...
%     'FitBoxToText', 'off');
% 
% annotation( ...
%     figSurface, ...
%     'textbox', ...
%     [0.45, 0.055, 0.37, 0.075], ...
%     'String', 'Hand direction, \theta_H', ...
%     'Interpreter', 'tex', ...
%     'FontName', 'Arial', ...
%     'FontSize', 17 * textScale, ...
%     'FontWeight', 'bold', ...
%     'HorizontalAlignment', 'center', ...
%     'VerticalAlignment', 'middle', ...
%     'EdgeColor', 'none', ...
%     'FitBoxToText', 'off');

%% ------------------------------------------------------------------------
% Colorbar
% -------------------------------------------------------------------------

cb = colorbar('peer', ax);

set(cb, ...
    'Units', 'normalized', ...
    'Position', [0.82, 0.22, 0.023, 0.65], ...
    'FontName', 'Arial', ...
    'FontSize', 12 * textScale, ...
    'LineWidth', 1.0);

ylabel( ...
    cb, ...
    'Firing rate [Hz]', ...
    'FontSize', 15 * textScale, ...
    'FontWeight', 'bold');

drawnow;

tightInset3D = get(ax, 'TightInset');

set(ax, ...
    'LooseInset', ...
    max(tightInset3D, [0.04, 0.04, 0.04, 0.04]));

%% ========================================================================
% FIGURE 2: Mean hand tuning curve
% =========================================================================

figHand = figure( ...
    'Color', 'w', ...
    'Units', 'inches', ...
    'Position', ...
    [1.0, 1.0, curveFigureWidth, curveFigureHeight], ...
    'Renderer', 'painters');

axHand = axes( ...
    'Parent', figHand, ...
    'Units', 'normalized', ...
    'Position', [0.29, 0.30, 0.62, 0.56]);

hold(axHand, 'on');

plot( ...
    axHand, ...
    thetaHand, ...
    meanHandCurve, ...
    'Color', handLineColor, ...
    'LineWidth', meanLineWidth);

xlim(axHand, [-pi, pi]);
ylim(axHand, [frMin, frMax]);

set(axHand, ...
    'FontName', 'Arial', ...
    'FontSize', 14 * textScale, ...
    'FontWeight', 'normal', ...
    'LineWidth', 1.2, ...
    'TickDir', 'out', ...
    'TickLength', [0.018, 0.018], ...
    'Box', 'off', ...
    'XColor', [0.12, 0.12, 0.12], ...
    'YColor', [0.12, 0.12, 0.12], ...
    'XTick', angularGridTicks, ...
    'XTickLabel', angleTickLabels, ...
    'YTick', curveYTicks);

grid(axHand, 'off');

xlabel( ...
    axHand, ...
    'Hand direction, \theta_H', ...
    'FontSize', 17 * textScale, ...
    'FontWeight', 'bold');

ylabel( ...
    axHand, ...
    'Firing rate [Hz]', ...
    'FontSize', 17 * textScale, ...
    'FontWeight', 'bold');

title( ...
    axHand, ...
    'Mean hand tuning', ...
    'FontSize', 17 * textScale, ...
    'FontWeight', 'bold');

drawnow;

tightInsetHand = get(axHand, 'TightInset');

set(axHand, ...
    'LooseInset', ...
    max(tightInsetHand, [0.04, 0.04, 0.04, 0.04]));

%% ========================================================================
% FIGURE 3: Mean eye tuning curve
% =========================================================================

figEye = figure( ...
    'Color', 'w', ...
    'Units', 'inches', ...
    'Position', ...
    [1.5, 1.5, curveFigureWidth, curveFigureHeight], ...
    'Renderer', 'painters');

axEye = axes( ...
    'Parent', figEye, ...
    'Units', 'normalized', ...
    'Position', [0.29, 0.30, 0.62, 0.56]);

hold(axEye, 'on');

plot( ...
    axEye, ...
    thetaEye, ...
    meanEyeCurve, ...
    'Color', eyeLineColor, ...
    'LineWidth', meanLineWidth);

xlim(axEye, [-pi, pi]);
ylim(axEye, [frMin, frMax]);

set(axEye, ...
    'FontName', 'Arial', ...
    'FontSize', 14 * textScale, ...
    'FontWeight', 'normal', ...
    'LineWidth', 1.2, ...
    'TickDir', 'out', ...
    'TickLength', [0.018, 0.018], ...
    'Box', 'off', ...
    'XColor', [0.12, 0.12, 0.12], ...
    'YColor', [0.12, 0.12, 0.12], ...
    'XTick', angularGridTicks, ...
    'XTickLabel', angleTickLabels, ...
    'YTick', curveYTicks);

grid(axEye, 'off');

xlabel( ...
    axEye, ...
    'Eye direction, \theta_E', ...
    'FontSize', 17 * textScale, ...
    'FontWeight', 'bold');

ylabel( ...
    axEye, ...
    'Firing rate [Hz]', ...
    'FontSize', 17 * textScale, ...
    'FontWeight', 'bold');

title( ...
    axEye, ...
    'Mean eye tuning', ...
    'FontSize', 17 * textScale, ...
    'FontWeight', 'bold');

drawnow;

tightInsetEye = get(axEye, 'TightInset');

set(axEye, ...
    'LooseInset', ...
    max(tightInsetEye, [0.04, 0.04, 0.04, 0.04]));

%% ========================================================================
% Save all three figures as PDFs
% =========================================================================

if saveFigures

    if ~exist(outputFolder, 'dir')
        mkdir(outputFolder);
    end

    surfaceOutputPath = ...
        fullfile(outputFolder, surfaceOutputName);

    handOutputPath = ...
        fullfile(outputFolder, handOutputName);

    eyeOutputPath = ...
        fullfile(outputFolder, eyeOutputName);

    %% --------------------------------------------------------------------
    % Save three-dimensional surface PDF
    % ---------------------------------------------------------------------

    if isgraphics(figSurface, 'figure')

        figure(figSurface);
        drawnow;

        tightInset3D = get(ax, 'TightInset');

        set(ax, ...
            'LooseInset', ...
            max(tightInset3D, [0.04, 0.04, 0.04, 0.04]));

        set(figSurface, ...
            'Units', 'inches', ...
            'PaperUnits', 'inches', ...
            'PaperSize', [figureWidth, figureHeight], ...
            'PaperPosition', [0, 0, figureWidth, figureHeight], ...
            'PaperPositionMode', 'manual', ...
            'InvertHardcopy', 'off');

        drawnow;

        print( ...
            gcf, ...
            surfaceOutputPath, ...
            '-dpdf');

    else

        warning( ...
            'The three-dimensional surface figure is no longer valid.');

    end

    %% --------------------------------------------------------------------
    % Save hand tuning PDF
    % ---------------------------------------------------------------------

    if isgraphics(figHand, 'figure')

        figure(figHand);
        drawnow;

        tightInsetHand = get(axHand, 'TightInset');

        set(axHand, ...
            'LooseInset', ...
            max(tightInsetHand, [0.04, 0.04, 0.04, 0.04]));

        set(figHand, ...
            'Units', 'inches', ...
            'PaperUnits', 'inches', ...
            'PaperSize', ...
            [curveFigureWidth, curveFigureHeight], ...
            'PaperPosition', ...
            [0, 0, curveFigureWidth, curveFigureHeight], ...
            'PaperPositionMode', 'manual', ...
            'InvertHardcopy', 'off');

        drawnow;

        print( ...
            gcf, ...
            handOutputPath, ...
            '-dpdf', ...
            '-painters');

    else

        warning( ...
            'The hand tuning figure is no longer valid.');

    end

    %% --------------------------------------------------------------------
    % Save eye tuning PDF
    % ---------------------------------------------------------------------

    if isgraphics(figEye, 'figure')

        figure(figEye);
        drawnow;

        tightInsetEye = get(axEye, 'TightInset');

        set(axEye, ...
            'LooseInset', ...
            max(tightInsetEye, [0.04, 0.04, 0.04, 0.04]));

        set(figEye, ...
            'Units', 'inches', ...
            'PaperUnits', 'inches', ...
            'PaperSize', ...
            [curveFigureWidth, curveFigureHeight], ...
            'PaperPosition', ...
            [0, 0, curveFigureWidth, curveFigureHeight], ...
            'PaperPositionMode', 'manual', ...
            'InvertHardcopy', 'off');

        drawnow;

        print( ...
            gcf, ...
            eyeOutputPath, ...
            '-dpdf', ...
            '-painters');

    else

        warning( ...
            'The eye tuning figure is no longer valid.');

    end

    fprintf( ...
        '\nPDF figures saved to:\n%s\n', ...
        outputFolder);

end

end
